version: '3.2'

networks:
  proxy:
    external: true
  internal:
    external: false


services:

  plp_reverse_proxy:
    container_name: plp_traefik

    # The official v2.0 Traefik docker image
    image: traefik:${TAG_TRAEFIK}
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true #### TO REMOVE FOR PRODUCTION #####
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - proxy




  plp_web:
    build: 
      context: ./web
      args:
        TAG_NODE: "${TAG_NODE}"
        TAG_VUECLI: "${TAG_VUECLI}"
    #ports: 
    #  - "8081:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.plp_web.entrypoints=http,https
      - traefik.http.routers.plp_web.rule=Host(`plp.localhost`)
      - traefik.http.services.plp_web.loadbalancer.server.port=8080
    networks:
      - internal
    depends_on:
      - plp_reverse_proxy
