version: '3.2'

networks:
  proxy:
    external: true
  internal:
    external: false




services:

  web:
    build: 
      context: ./web
      args:
        TAG_NODE: "${TAG_NODE}"
        TAG_VUECLI: "${TAG_VUECLI}"
    ports: 
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.backend=plp_web
      - traefik.docker.network=proxy
      - traefik.port=8081
      - traefik.frontend.entrypoints=http,https
    networks:
      - internal
      - proxy
    #depends_on:
    #  - decision
