version: '3'
services:

  web:
    container_name: plp_web
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - ./web:/app
      - '/app/node_modules'
