version: '3.2'

networks:
  proxy:
    external: true
  internal:
    external: false


services:

  plp_reverse_proxy:
    container_name: plp_traefik

    image: traefik:${TAG_TRAEFIK}
    command: 
      - --api
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=bin@mgarrigues.fr
      - --certificatesresolvers.le.acme.storage=etc/traefik/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true

    labels:
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=http"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=https

       # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      ### Next line's '$' are doubled as to escape them
      - traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$Qai983Ya$$XNOr.GZjn3Uggtu3iHqbY/

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - proxy




  plp_web:
    build: 
      context: ./web
      args:
        TAG_NODE: "${TAG_NODE}"
        TAG_VUECLI: "${TAG_VUECLI}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.plp_web.rule=Host(`plp.localhost`)
      - traefik.http.services.plp_web.loadbalancer.server.port=8080
      - traefik.http.routers.plp_web.tls.certresolver=le
      - traefik.http.routers.plp_web.entrypoints=https"
    networks:
      - internal
    depends_on:
      - plp_reverse_proxy
