version: '3.2'

services:

  plp_reverse_proxy:
    container_name: plp_traefik_prod
    command:
      - --api
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=bin@mgarrigues.fr
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    labels:

      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=http"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"


      - traefik.http.routers.traefik.rule=Host(`${PROD_TRAEFIK_PATH}`)
      - traefik.http.routers.traefik.tls.certresolver=leresolver
      - traefik.http.routers.traefik.entrypoints=https, http

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"




  plp_web:
    container_name: plp_web_prod
    build:
      dockerfile: Dockerfile.prod
    image: im_plp_web_prod
    labels:

      - traefik.http.routers.plp_web.rule=Host(`${PROD_PLP_PATH}`)
      - traefik.http.routers.plp_web.tls.certresolver=leresolver
      - traefik.http.routers.plp_web.entrypoints=https, http

  plp_api:
    container_name: plp_api_prod
    image: im_plp_api_prod
    labels:

      - traefik.http.routers.plp_api.rule=Host(`${PROD_API_PATH}`)
      - traefik.http.routers.plp_api.tls.certresolver=leresolver
      - traefik.http.routers.plp_api.entrypoints=http,https


  mongo-seed:
    build: ./etc/mongo-seed
    links:
      - plp_mongodb
    depends_on:
      - plp_mongodb
    restart: on-failure
    networks:
      - internal
      - proxy #temporary, need to find fix