# Set the base image
ARG TAGJENKINS
FROM jenkins/jenkins:lts-alpine

# Set working directory
WORKDIR /home/jenkins

USER root

USER jenkins

#CMD ls /var/jenkins_home
#COPY plp_jenkins:/var/jenkins_home/secrets/initialAdminPassword .