pipeline {
   agent { docker { image 'python:3.7.2' } }
   String cron_string = BRANCH_NAME == "master" ? "@hourly" : ""
   triggers { cron(cron_string) }
   stages {
     stage('build env') {
       steps {
         echo 'Building ***'
         sh 'pip install -r decision/PLP_ML/requirements.txt && jupyter --version'
       }
     }
     stage('get datas') {
       steps {
         sh 'jupyter nbconvert --execute --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=2000 decision/PLP_ML/PipelineGetRawData.ipynb'
         sh 'jupyter nbconvert --execute --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=2000 decision/PLP_ML/PipelineDeRrrrafinnage.ipynb'
       }
     }
     stage('train ML') {
       steps {
         sh 'jupyter nbconvert --execute --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=600 decision/PLP_ML/ML.ipynb'
     }
     stage('predict ML') {
       steps {
         sh 'jupyter nbconvert --execute --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=600 decision/PLP_ML/MLPredict.ipynb'
     }
   }
 }
