name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    #- name: Build the web Docker image
     # run: docker build web --file Dockerfile --tag plp_web:$(date +%s)

    #- name: Build the decision Docker image
     # run: docker build decision --file Dockerfile --tag plp_decision:$(date +%s)
