ARG TAG_NODE

# base image
FROM node:$TAG_NODE

# set working directory
WORKDIR /app

# install simple http server for serving static content
RUN npm install -g http-server

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json


RUN npm install
RUN npm install @vue/cli@3.7.0 -g
RUN npm run build

# start app
CMD ["http-serv", "dist"]