ARG TAG_NODE
ARG TAG_VUECLI

# base image
FROM node:$TAG_NODE

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json

RUN npm install
RUN npm install @vue/cli@$TAG_VUECLI -g

# start app
CMD ["npm", "run", "serve"]